/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pms;

import java.awt.*;
import java.awt.event.*;
import java.awt.image.BufferedImage;
import javax.swing.*;
import java.io.*;

import javax.imageio.ImageIO;


public class MainFrame extends javax.swing.JFrame 
{

    private static final long serialVersionUID = 1L;

    Point startPos = new Point(0,0);
    Point endPos = new Point(0,0);

    //The folder your created pictures will be placed
    String NEWFILEPATH;
    //Change to the location of your sentinel executable
    static File EXEFILEPATH;
    //The new name of the created bmp pic
    String NEWPICNAME;
    final JFileChooser fc = new JFileChooser();
    File originalFile;
    File chosenFile;
    File createdFile;
    BufferedImage image;
    String pictureLocation;
    public Object obj;
    JFrame frame;
    JFrame frame2;
    JFrame frame3;
    Color filter;
    int filterValue;
    String colorChoice;
    String temp;
    Color oneColor;
    Color twoColor;
    int selectedValue;
    //instance of Main class to get the .exe file path 
    //Main ec = new Main();


    public static void main (String[] args)
    {
        new MainFrame().setVisible(true);
    }

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();

        JFileChooser jfc = new JFileChooser();
        switch(jfc.showOpenDialog(this))
        {
            case JFileChooser.APPROVE_OPTION: EXEFILEPATH = jfc.getSelectedFile(); break;
            case JFileChooser.CANCEL_OPTION: System.exit(1); break;
            case JFileChooser.ERROR_OPTION: System.exit(1); break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TintGroup = new javax.swing.ButtonGroup();
        rotateFrame = new javax.swing.JFrame();
        degrees = new javax.swing.JComboBox<String>();
        rotateButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        filterFrame = new javax.swing.JFrame();
        filterLabel = new javax.swing.JLabel();
        filterScale = new javax.swing.JSlider();
        filterLabel1 = new javax.swing.JLabel();
        filterColorChooser = new javax.swing.JColorChooser();
        filterExit = new javax.swing.JButton();
        tintFrame = new javax.swing.JFrame();
        tintButton = new javax.swing.JButton();
        Blue = new javax.swing.JRadioButton();
        Red = new javax.swing.JRadioButton();
        Green = new javax.swing.JRadioButton();
        tintLabel = new javax.swing.JLabel();
        resizeFrame = new javax.swing.JFrame();
        doubleViewButton = new javax.swing.JRadioButton();
        doubleFileButton = new javax.swing.JRadioButton();
        submitResize = new javax.swing.JToggleButton();
        resizeLabel = new javax.swing.JLabel();
        twoToneFrame = new javax.swing.JFrame();
        twoColorChooser = new javax.swing.JColorChooser();
        oneColorChooser = new javax.swing.JColorChooser();
        twoColorButton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        compressFrame = new javax.swing.JFrame();
        sixteenButton = new javax.swing.JRadioButton();
        rleComButton = new javax.swing.JRadioButton();
        rleDecomButton = new javax.swing.JRadioButton();
        compressoinLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        StretchGroup = new javax.swing.ButtonGroup();
        stretchFrame = new javax.swing.JFrame();
        Vertical = new javax.swing.JRadioButton();
        Horizontal = new javax.swing.JRadioButton();
        stretchLabel = new javax.swing.JLabel();
        submitStretch = new javax.swing.JToggleButton();
        resizeGroup = new javax.swing.ButtonGroup();
        compressGroup = new javax.swing.ButtonGroup();
        cwFrame = new javax.swing.JFrame();
        blackWhiteButton = new javax.swing.JRadioButton();
        blueWhiteButton = new javax.swing.JRadioButton();
        greenWhiteButton = new javax.swing.JRadioButton();
        redWhiteButton = new javax.swing.JRadioButton();
        cwSlider = new javax.swing.JSlider();
        cwLabel = new javax.swing.JLabel();
        cwSubmit = new javax.swing.JButton();
        cwGroup = new javax.swing.ButtonGroup();
        flipFrame = new javax.swing.JFrame();
        verticalButton = new javax.swing.JRadioButton();
        horizontalButton = new javax.swing.JRadioButton();
        flipLabel = new javax.swing.JLabel();
        flipSubmit = new javax.swing.JButton();
        flipGroup = new javax.swing.ButtonGroup();
        mainTitle = new javax.swing.JLabel();
        CW = new javax.swing.JButton();
        grayScale = new javax.swing.JButton();
        tint = new javax.swing.JButton();
        twoTone = new javax.swing.JButton();
        negatize = new javax.swing.JButton();
        sepia = new javax.swing.JButton();
        upload = new javax.swing.JButton();
        blur = new javax.swing.JButton();
        stretch = new javax.swing.JButton();
        rotate = new javax.swing.JButton();
        crop = new javax.swing.JButton();
        //        jPanel1 = new javax.swing.JPanel();
        jPanel1 = new ImagePanel();
        picLabel = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        choosePicture = new javax.swing.JButton();
        filterButton = new javax.swing.JButton();
        resizeButton = new javax.swing.JButton();
        Compress = new javax.swing.JButton();
        originalPicture = new javax.swing.JButton();
        flip = new javax.swing.JButton();
        selectAll = new javax.swing.JCheckBox();

        degrees.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "90 Degrees to the Left", "90 Degrees to the Right", "180 Degrees" }));
        degrees.setAutoscrolls(true);

        rotateButton.setText("Submit");
        rotateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24));
        jLabel4.setText("Rotate");

        javax.swing.GroupLayout rotateFrameLayout = new javax.swing.GroupLayout(rotateFrame.getContentPane());
        rotateFrame.getContentPane().setLayout(rotateFrameLayout);
        rotateFrameLayout.setHorizontalGroup(
                                             rotateFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rotateFrameLayout.createSequentialGroup()
                                                       .addContainerGap(84, Short.MAX_VALUE)
                                                       .addComponent(degrees, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                       .addGap(74, 74, 74))
                                                       .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rotateFrameLayout.createSequentialGroup()
                                                                 .addContainerGap(138, Short.MAX_VALUE)
                                                                 .addComponent(rotateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                 .addGap(130, 130, 130))
                                                                 .addGroup(rotateFrameLayout.createSequentialGroup()
                                                                           .addGap(129, 129, 129)
                                                                           .addComponent(jLabel4)
                                                                           .addContainerGap(197, Short.MAX_VALUE))
                );
        rotateFrameLayout.setVerticalGroup(
                                           rotateFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                           .addGroup(rotateFrameLayout.createSequentialGroup()
                                                     .addContainerGap()
                                                     .addComponent(jLabel4)
                                                     .addGap(64, 64, 64)
                                                     .addComponent(degrees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                     .addGap(65, 65, 65)
                                                     .addComponent(rotateButton)
                                                     .addContainerGap(65, Short.MAX_VALUE))
                );

        filterLabel.setText("Choose filter value: ");

        filterScale.setMajorTickSpacing(10);
        filterScale.setMinorTickSpacing(5);
        filterScale.setPaintLabels(true);
        filterScale.setPaintTicks(true);
        filterScale.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        filterLabel1.setText("Choose filter color: ");

        filterExit.setText("Submit");
        filterExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filterFrameLayout = new javax.swing.GroupLayout(filterFrame.getContentPane());
        filterFrame.getContentPane().setLayout(filterFrameLayout);
        filterFrameLayout.setHorizontalGroup(
                                             filterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addGroup(filterFrameLayout.createSequentialGroup()
                                                       .addGroup(filterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                 .addGroup(filterFrameLayout.createSequentialGroup()
                                                                           .addContainerGap()
                                                                           .addComponent(filterColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                           .addGroup(filterFrameLayout.createSequentialGroup()
                                                                                     .addGap(167, 167, 167)
                                                                                     .addComponent(filterLabel1))
                                                                                     .addGroup(filterFrameLayout.createSequentialGroup()
                                                                                               .addGap(160, 160, 160)
                                                                                               .addComponent(filterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                               .addGroup(filterFrameLayout.createSequentialGroup()
                                                                                                         .addGap(44, 44, 44)
                                                                                                         .addComponent(filterScale, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                         .addGroup(filterFrameLayout.createSequentialGroup()
                                                                                                                   .addGap(187, 187, 187)
                                                                                                                   .addComponent(filterExit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                   .addContainerGap(54, Short.MAX_VALUE))
                );
        filterFrameLayout.setVerticalGroup(
                                           filterFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                           .addGroup(filterFrameLayout.createSequentialGroup()
                                                     .addContainerGap()
                                                     .addComponent(filterLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                     .addGap(4, 4, 4)
                                                     .addComponent(filterColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                     .addGap(18, 18, 18)
                                                     .addComponent(filterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                     .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                     .addComponent(filterScale, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                     .addGap(18, 18, 18)
                                                     .addComponent(filterExit)
                                                     .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

        tintButton.setText("Select Color");
        tintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tintButtonActionPerformed(evt);
            }
        });

        Blue.setText("Blue");

        Red.setText("Red");

        Green.setText("Green");

        tintLabel.setFont(new java.awt.Font("Lucida Grande", 3, 18));
        tintLabel.setText("Select tint color: ");

        javax.swing.GroupLayout tintFrameLayout = new javax.swing.GroupLayout(tintFrame.getContentPane());
        tintFrame.getContentPane().setLayout(tintFrameLayout);
        tintFrameLayout.setHorizontalGroup(
                                           tintFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tintFrameLayout.createSequentialGroup()
                                                     .addContainerGap(84, Short.MAX_VALUE)
                                                     .addGroup(tintFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                               .addComponent(Blue)
                                                               .addComponent(Red)
                                                               .addComponent(Green))
                                                               .addGap(248, 248, 248))
                                                               .addGroup(tintFrameLayout.createSequentialGroup()
                                                                         .addGap(132, 132, 132)
                                                                         .addComponent(tintButton)
                                                                         .addContainerGap(149, Short.MAX_VALUE))
                                                                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tintFrameLayout.createSequentialGroup()
                                                                                   .addContainerGap(116, Short.MAX_VALUE)
                                                                                   .addComponent(tintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                   .addGap(109, 109, 109))
                );
        tintFrameLayout.setVerticalGroup(
                                         tintFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                         .addGroup(tintFrameLayout.createSequentialGroup()
                                                   .addGap(8, 8, 8)
                                                   .addComponent(tintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                   .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                   .addComponent(Red)
                                                   .addGap(26, 26, 26)
                                                   .addComponent(Green)
                                                   .addGap(30, 30, 30)
                                                   .addComponent(Blue)
                                                   .addGap(39, 39, 39)
                                                   .addComponent(tintButton)
                                                   .addContainerGap(48, Short.MAX_VALUE))
                );

        doubleViewButton.setText("Double Viewing Size");

        doubleFileButton.setText("Double File Data");

        submitResize.setText("Submit");
        submitResize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitResizeActionPerformed(evt);
            }
        });

        resizeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24));
        resizeLabel.setText("Resize");

        javax.swing.GroupLayout resizeFrameLayout = new javax.swing.GroupLayout(resizeFrame.getContentPane());
        resizeFrame.getContentPane().setLayout(resizeFrameLayout);
        resizeFrameLayout.setHorizontalGroup(
                                             resizeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addGroup(resizeFrameLayout.createSequentialGroup()
                                                       .addGroup(resizeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                 .addGroup(resizeFrameLayout.createSequentialGroup()
                                                                           .addGap(61, 61, 61)
                                                                           .addGroup(resizeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                     .addComponent(doubleFileButton)
                                                                                     .addComponent(doubleViewButton)))
                                                                                     .addGroup(resizeFrameLayout.createSequentialGroup()
                                                                                               .addGap(89, 89, 89)
                                                                                               .addComponent(resizeLabel)))
                                                                                               .addContainerGap(49, Short.MAX_VALUE))
                                                                                               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resizeFrameLayout.createSequentialGroup()
                                                                                                         .addContainerGap(92, Short.MAX_VALUE)
                                                                                                         .addComponent(submitResize)
                                                                                                         .addGap(89, 89, 89))
                );
        resizeFrameLayout.setVerticalGroup(
                                           resizeFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                           .addGroup(resizeFrameLayout.createSequentialGroup()
                                                     .addContainerGap()
                                                     .addComponent(resizeLabel)
                                                     .addGap(38, 38, 38)
                                                     .addComponent(doubleViewButton)
                                                     .addGap(31, 31, 31)
                                                     .addComponent(doubleFileButton)
                                                     .addGap(29, 29, 29)
                                                     .addComponent(submitResize)
                                                     .addContainerGap(30, Short.MAX_VALUE))
                );

        twoColorButton.setText("Submit");
        twoColorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoColorButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24));
        jLabel1.setText("Two Tone");

        javax.swing.GroupLayout twoToneFrameLayout = new javax.swing.GroupLayout(twoToneFrame.getContentPane());
        twoToneFrame.getContentPane().setLayout(twoToneFrameLayout);
        twoToneFrameLayout.setHorizontalGroup(
                                              twoToneFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                              .addGroup(twoToneFrameLayout.createSequentialGroup()
                                                        .addGroup(twoToneFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                  .addGroup(twoToneFrameLayout.createSequentialGroup()
                                                                            .addContainerGap()
                                                                            .addComponent(twoColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                            .addComponent(oneColorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                            .addGroup(twoToneFrameLayout.createSequentialGroup()
                                                                                      .addGap(388, 388, 388)
                                                                                      .addComponent(twoColorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                      .addGroup(twoToneFrameLayout.createSequentialGroup()
                                                                                                .addGap(395, 395, 395)
                                                                                                .addComponent(jLabel1)))
                                                                                                .addContainerGap(33, Short.MAX_VALUE))
                );
        twoToneFrameLayout.setVerticalGroup(
                                            twoToneFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, twoToneFrameLayout.createSequentialGroup()
                                                      .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                      .addComponent(jLabel1)
                                                      .addGap(18, 18, 18)
                                                      .addGroup(twoToneFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(twoColorChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(oneColorChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(28, 28, 28)
                                                                .addComponent(twoColorButton)
                                                                .addContainerGap())
                );

        sixteenButton.setText("16 bit");

        rleComButton.setText("RLE Compress");

        rleDecomButton.setText("RLE Decompress");

        compressoinLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24));
        compressoinLabel.setText("Compression Options");

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout compressFrameLayout = new javax.swing.GroupLayout(compressFrame.getContentPane());
        compressFrame.getContentPane().setLayout(compressFrameLayout);
        compressFrameLayout.setHorizontalGroup(
                                               compressFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, compressFrameLayout.createSequentialGroup()
                                                         .addContainerGap(75, Short.MAX_VALUE)
                                                         .addComponent(compressoinLabel)
                                                         .addGap(72, 72, 72))
                                                         .addGroup(compressFrameLayout.createSequentialGroup()
                                                                   .addGap(126, 126, 126)
                                                                   .addGroup(compressFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                             .addComponent(rleComButton)
                                                                             .addComponent(sixteenButton)
                                                                             .addComponent(rleDecomButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                             .addContainerGap(138, Short.MAX_VALUE))
                                                                             .addGroup(compressFrameLayout.createSequentialGroup()
                                                                                       .addGap(156, 156, 156)
                                                                                       .addComponent(jButton1)
                                                                                       .addContainerGap(156, Short.MAX_VALUE))
                );
        compressFrameLayout.setVerticalGroup(
                                             compressFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                             .addGroup(compressFrameLayout.createSequentialGroup()
                                                       .addGap(42, 42, 42)
                                                       .addComponent(compressoinLabel)
                                                       .addGap(41, 41, 41)
                                                       .addComponent(sixteenButton)
                                                       .addGap(18, 18, 18)
                                                       .addComponent(rleComButton)
                                                       .addGap(18, 18, 18)
                                                       .addComponent(rleDecomButton)
                                                       .addGap(27, 27, 27)
                                                       .addComponent(jButton1)
                                                       .addContainerGap(26, Short.MAX_VALUE))
                );

        Vertical.setText("Vertical");

        Horizontal.setText("Horizontal");

        stretchLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24));
        stretchLabel.setText("Stretch");

        submitStretch.setText("Submit");
        submitStretch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitStretchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout stretchFrameLayout = new javax.swing.GroupLayout(stretchFrame.getContentPane());
        stretchFrame.getContentPane().setLayout(stretchFrameLayout);
        stretchFrameLayout.setHorizontalGroup(
                                              stretchFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                              .addGroup(stretchFrameLayout.createSequentialGroup()
                                                        .addGroup(stretchFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stretchFrameLayout.createSequentialGroup()
                                                                            .addGap(99, 99, 99)
                                                                            .addGroup(stretchFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                      .addComponent(Vertical, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                                                                      .addComponent(Horizontal, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                                                                      .addComponent(submitStretch)))
                                                                                      .addGroup(stretchFrameLayout.createSequentialGroup()
                                                                                                .addGap(107, 107, 107)
                                                                                                .addComponent(stretchLabel)))
                                                                                                .addContainerGap())
                );
        stretchFrameLayout.setVerticalGroup(
                                            stretchFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(stretchFrameLayout.createSequentialGroup()
                                                      .addContainerGap()
                                                      .addComponent(stretchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                      .addGap(18, 18, 18)
                                                      .addComponent(Horizontal)
                                                      .addGap(18, 18, 18)
                                                      .addComponent(Vertical)
                                                      .addGap(39, 39, 39)
                                                      .addComponent(submitStretch)
                                                      .addContainerGap(54, Short.MAX_VALUE))
                );

        blackWhiteButton.setText("Black & White");

        blueWhiteButton.setText("Blue & White");

        greenWhiteButton.setText("Green & White");

        redWhiteButton.setText("Red & White");

        cwSlider.setMajorTickSpacing(100);
        cwSlider.setMaximum(750);
        cwSlider.setMinorTickSpacing(5);
        cwSlider.setPaintLabels(true);
        cwSlider.setPaintTicks(true);
        cwSlider.setValue(250);

        cwLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24));
        cwLabel.setText("Color & White");

        cwSubmit.setText("Submit");
        cwSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cwSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout cwFrameLayout = new javax.swing.GroupLayout(cwFrame.getContentPane());
        cwFrame.getContentPane().setLayout(cwFrameLayout);
        cwFrameLayout.setHorizontalGroup(
                                         cwFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                         .addGroup(cwFrameLayout.createSequentialGroup()
                                                   .addGroup(cwFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                             .addGroup(cwFrameLayout.createSequentialGroup()
                                                                       .addGap(98, 98, 98)
                                                                       .addGroup(cwFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                 .addComponent(redWhiteButton)
                                                                                 .addComponent(greenWhiteButton)
                                                                                 .addComponent(blueWhiteButton)
                                                                                 .addComponent(blackWhiteButton)))
                                                                                 .addGroup(cwFrameLayout.createSequentialGroup()
                                                                                           .addGap(106, 106, 106)
                                                                                           .addComponent(cwLabel))
                                                                                           .addGroup(cwFrameLayout.createSequentialGroup()
                                                                                                     .addGap(148, 148, 148)
                                                                                                     .addComponent(cwSubmit)))
                                                                                                     .addContainerGap(132, Short.MAX_VALUE))
                                                                                                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cwFrameLayout.createSequentialGroup()
                                                                                                               .addContainerGap(33, Short.MAX_VALUE)
                                                                                                               .addComponent(cwSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                               .addGap(25, 25, 25))
                );
        cwFrameLayout.setVerticalGroup(
                                       cwFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addGroup(cwFrameLayout.createSequentialGroup()
                                                 .addGap(29, 29, 29)
                                                 .addComponent(cwLabel)
                                                 .addGap(29, 29, 29)
                                                 .addComponent(blackWhiteButton)
                                                 .addGap(18, 18, 18)
                                                 .addComponent(blueWhiteButton)
                                                 .addGap(18, 18, 18)
                                                 .addComponent(greenWhiteButton)
                                                 .addGap(18, 18, 18)
                                                 .addComponent(redWhiteButton)
                                                 .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                                 .addComponent(cwSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                 .addGap(30, 30, 30)
                                                 .addComponent(cwSubmit)
                                                 .addGap(34, 34, 34))
                );

        verticalButton.setText("Vertical");

        horizontalButton.setText("Horizontal");

        flipLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24));
        flipLabel.setText("Flip");

        flipSubmit.setText("Submit");
        flipSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flipSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout flipFrameLayout = new javax.swing.GroupLayout(flipFrame.getContentPane());
        flipFrame.getContentPane().setLayout(flipFrameLayout);
        flipFrameLayout.setHorizontalGroup(
                                           flipFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                           .addGroup(flipFrameLayout.createSequentialGroup()
                                                     .addGap(123, 123, 123)
                                                     .addGroup(flipFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                               .addGroup(flipFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                         .addComponent(flipLabel)
                                                                         .addComponent(verticalButton))
                                                                         .addGroup(flipFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                   .addComponent(flipSubmit)
                                                                                   .addComponent(horizontalButton)))
                                                                                   .addContainerGap(138, Short.MAX_VALUE))
                );
        flipFrameLayout.setVerticalGroup(
                                         flipFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                         .addGroup(flipFrameLayout.createSequentialGroup()
                                                   .addGap(35, 35, 35)
                                                   .addComponent(flipLabel)
                                                   .addGap(30, 30, 30)
                                                   .addComponent(verticalButton)
                                                   .addGap(18, 18, 18)
                                                   .addComponent(horizontalButton)
                                                   .addGap(31, 31, 31)
                                                   .addComponent(flipSubmit)
                                                   .addContainerGap(64, Short.MAX_VALUE))
                );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainTitle.setFont(new java.awt.Font("Tahoma", 0, 24));
        mainTitle.setText("Photo Manipulator");

        CW.setText("Color & White");
        CW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CWActionPerformed(evt);
            }
        });

        grayScale.setText("Gray Scale");
        grayScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grayScaleActionPerformed(evt);
                submitActionPerformed(evt);
            }
        });

        tint.setText("Tint");
        tint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tintActionPerformed(evt);
            }
        });

        twoTone.setText("Two Tone");
        twoTone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoToneHandler(evt);
                submitActionPerformed(evt);
            }
        });

        negatize.setText("Negatize");
        negatize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negatizeActionPerformed(evt);
                submitActionPerformed(evt);
            }
        });

        sepia.setText("Sepia");
        sepia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sepiaActionPerformed(evt);
                submitActionPerformed(evt);
            }
        });

        upload.setText("Imgur");
        upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadActionPerformed(evt);
            }
        });
        
        blur.setText("Blur");
        blur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blurActionPerformed(evt);
                submitActionPerformed(evt);
            }
        });

        selectAll.setText("Select All");
        selectAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectAllActionPerformed(evt);
            }
        });

        stretch.setText("Stretch");
        stretch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stretchActionPerformed(evt);
                submitActionPerformed(evt);
            }
        });

        rotate.setText("Rotate");
        rotate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotateActionPerformed(evt);
                submitActionPerformed(evt);
            }
        });

        crop.setText("Crop");
        crop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cropActionPerformed(evt);
                submitActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                                         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                         .addComponent(picLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                );
        jPanel1Layout.setVerticalGroup(
                                       jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                       .addComponent(picLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
                );

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitHandler(evt);
            }
        });

        choosePicture.setText("Choose Picture");
        choosePicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosePictureActionPerformed(evt);
            }
        });

        filterButton.setText("Filter");
        filterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButtonActionPerformed(evt);
            }
        });

        resizeButton.setText("Resize");
        resizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resizeButtonActionPerformed(evt);
            }
        });

        Compress.setText("Compress");
        Compress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompressActionPerformed(evt);
            }
        });

        originalPicture.setText("Original Picture");
        originalPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                originalPictureActionPerformed(evt);
            }
        });

        flip.setText("Flip");
        flip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flipActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                  .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                      .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                          .addGroup(layout.createSequentialGroup()
                                                                                    .addContainerGap()
                                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                              .addComponent(CW, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                                                                              .addComponent(grayScale, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                                                                              .addComponent(tint, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                                                                              .addComponent(stretch, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                                                                              .addComponent(rotate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                                                                              .addComponent(sepia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                                                                              .addComponent(upload, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                                                                              .addComponent(filterButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                                                                                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                        .addComponent(negatize, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                                                                                        .addComponent(twoTone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                                                                                        .addComponent(resizeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                                                                                        .addComponent(Compress, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                                                                                        .addComponent(crop, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                                                                                        .addComponent(blur, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                                                                                        .addComponent(flip, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                                                                                                        .addGroup(layout.createSequentialGroup()
                                                                                                                  .addGap(105, 105, 105)
                                                                                                                  .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                                                            .addGroup(layout.createSequentialGroup()
                                                                                                                                      .addComponent(choosePicture)
                                                                                                                                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                      .addComponent(originalPicture)
                                                                                                                                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                      .addComponent(exit)
                                                                                                                                      .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                      .addComponent(selectAll))))
                                                                                                                                      .addGroup(layout.createSequentialGroup()
                                                                                                                                                .addGap(260, 260, 260)
                                                                                                                                                .addComponent(mainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                                                                                                .addContainerGap())
                );
        layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                          .addContainerGap()
                                          .addComponent(mainTitle)
                                          .addGap(32,32,32)
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(CW)
                                                                        .addComponent(negatize))
                                                                        .addGap(18, 18, 18)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                  .addComponent(twoTone)
                                                                                  .addComponent(grayScale))
                                                                                  .addGap(18, 18, 18)
                                                                                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                            .addComponent(tint)
                                                                                            .addComponent(resizeButton))
                                                                                            .addGap(18, 18, 18)
                                                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                      .addComponent(stretch)
                                                                                                      .addComponent(flip))
                                                                                                      .addGap(18, 18, 18)
                                                                                                      .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                .addComponent(crop)
                                                                                                                .addComponent(rotate))
                                                                                                                .addGap(18, 18, 18)
                                                                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                          .addComponent(filterButton)
                                                                                                                          .addComponent(Compress))
                                                                                                                          .addGap(18, 18, 18)
                                                                                                                          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                    .addComponent(sepia)
                                                                                                                                    .addComponent(blur))
                                                                                                                                    .addGap(18, 18, 18)
                                                                                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                    .addComponent(upload)))
//                                                                                                                                    .addComponent(blur))
//                                                                                                                                    .addGap(64, 64, 64))
                                                                                                                                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                                                    .addGap(129, 129, 129)
                                                                                                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                                                                                              .addComponent(choosePicture)
                                                                                                                                              .addComponent(originalPicture)
                                                                                                                                              .addComponent(exit)
                                                                                                                                              .addComponent(selectAll))
                                                                                                                                              .addGap(49, 49, 49))
                                                                                                                                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                                                                                        .addContainerGap(425, Short.MAX_VALUE)
                                                                                                                                                        .addComponent(submit)
                                                                                                                                                        .addGap(82, 82, 82))
                );
        submit.setVisible(false);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grayScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grayScaleActionPerformed
        try {
            // Create file 
            FileWriter fstream = new FileWriter("pmsInfo.txt");
            BufferedWriter out = new BufferedWriter(fstream);
            //            out.write(pictureLocation + " 6 nil");
            out.write(pictureLocation + " 6 "+getFilterSize());
            selectedValue = 6;
            //Close the output stream
            out.close();
        } catch (Exception e) {//Catch exception if any
            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_grayScaleActionPerformed

    private void twoToneHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoToneHandler

        JPanel temp = new JPanel();
        temp.setLayout(new BoxLayout(temp, BoxLayout.Y_AXIS));
        twoToneFrame.getContentPane().add(BorderLayout.CENTER, temp);
        twoToneFrame.setSize(900, 500);
        twoToneFrame.setVisible(true);

    }//GEN-LAST:event_twoToneHandler

    private void exitHandler(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitHandler

        System.exit(0);
    }//GEN-LAST:event_exitHandler

    private void choosePictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosePictureActionPerformed
        // Get bmp file 
        if (evt.getSource() == choosePicture) {
            //filter that ensures only bmp files are selected
            fc.setFileFilter(new BmpFileFilter());
            int returnVal = fc.showOpenDialog(null);

            try {
                if (returnVal == JFileChooser.APPROVE_OPTION) {
                    chosenFile = fc.getSelectedFile();
                    originalFile = chosenFile;
                    //Display image in GUI
                    Dimension dm = new Dimension(picLabel.getHeight(), picLabel.getWidth());
                    picLabel.setPreferredSize(dm);
                    setImage(chosenFile);

                } else {
                    JOptionPane.showMessageDialog(null, JOptionPane.WARNING_MESSAGE);

                }
            } catch (Exception e) {//Catch exception if any
                System.err.println("Error: " + e.getMessage());
            }
        }

        //string location saved to be written to file for ACL2 to reference 
        pictureLocation = chosenFile.getPath();
        int index = pictureLocation.indexOf(".");
        NEWFILEPATH = pictureLocation.substring(0, index);


    }//GEN-LAST:event_choosePictureActionPerformed

    private void CWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CWActionPerformed

        JPanel temp = new JPanel();
        temp.setLayout(new BoxLayout(temp, BoxLayout.Y_AXIS));
        cwFrame.getContentPane().add(BorderLayout.CENTER, temp);
        cwFrame.setSize(400, 450);
        cwFrame.setVisible(true);
        cwGroup.add(blackWhiteButton);
        cwGroup.add(blueWhiteButton);
        cwGroup.add(greenWhiteButton);
        cwGroup.add(redWhiteButton);

    }//GEN-LAST:event_CWActionPerformed

    private void negatizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negatizeActionPerformed
        try {

            // Create file 
            FileWriter fstream = new FileWriter("pmsInfo.txt");
            BufferedWriter out = new BufferedWriter(fstream);
            //            out.write(pictureLocation + " 10 nil");
            out.write(pictureLocation + " 10 "+getFilterSize());
            selectedValue = 10;
            //Close the output stream
            out.close();
        } catch (Exception e) {//Catch exception if any
            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_negatizeActionPerformed

    private void sepiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negatizeActionPerformed
        try {

            // Create file 
            FileWriter fstream = new FileWriter("pmsInfo.txt");
            BufferedWriter out = new BufferedWriter(fstream);
            //            out.write(pictureLocation + " 10 nil");
            out.write(pictureLocation + " 25 "+getFilterSize());
            selectedValue = 25;
            //Close the output stream
            out.close();
        } catch (Exception e) {//Catch exception if any
            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_sepiaActionPerformed

    private void blurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negatizeActionPerformed
        try {

            // Create file 
            FileWriter fstream = new FileWriter("pmsInfo.txt");
            BufferedWriter out = new BufferedWriter(fstream);
            //            out.write(pictureLocation + " 10 nil");
            out.write(pictureLocation + " 26 "+getFilterSize());
            selectedValue = 26;
            //Close the output stream
            out.close();
        } catch (Exception e) {//Catch exception if any
            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_sepiaActionPerformed

    private void uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negatizeActionPerformed
        try {

            String name = JOptionPane.showInputDialog("Name of image?");

            Uploader up = new Uploader(name, createdFile);
            String json = up.Upload();

            String[] json_a = json.split("[{}\\s*,\"]", 0);

            String link = (json_a[17].replace("\\", "")).replace(".png", "");
            System.out.println(link);

            up.openLink(link);
            
        } catch (Exception e) {//Catch exception if any
            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_sepiaActionPerformed

    private void selectAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negatizeActionPerformed
        if (selectAll.isSelected())
        {
            startPos = new Point(0,0);
            if (image != null)
            {
                endPos = new Point(image.getWidth(),image.getHeight());
            }
        }
    }//GEN-LAST:event_sepiaActionPerformed

    private void stretchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stretchActionPerformed

        JPanel temp = new JPanel();
        temp.setLayout(new BoxLayout(temp, BoxLayout.Y_AXIS));
        stretchFrame.getContentPane().add(BorderLayout.CENTER, temp);
        stretchFrame.setSize(350, 350);
        stretchFrame.setVisible(true);
        StretchGroup.add(Vertical);
        StretchGroup.add(Horizontal);



    }//GEN-LAST:event_stretchActionPerformed

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed


        JPanel temp = new JPanel();
        temp.setLayout(new BoxLayout(temp, BoxLayout.Y_AXIS));
        filterFrame.getContentPane().add(BorderLayout.CENTER, temp);
        filterFrame.setSize(500, 650);
        filterFrame.setVisible(true);


    }//GEN-LAST:event_filterButtonActionPerformed

    private void filterExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterExitActionPerformed

        ColorStringToNum cs = new ColorStringToNum();
        filter = filterColorChooser.getColor();
        String values = cs.colorToNum(filter.toString(), 1);
        //x/100 = y/255, solve for y to get values in range of 255
        filterValue = (int) (filterScale.getValue() * 0.01 * 255);

        try {
            // Create file 
            FileWriter fstream = new FileWriter("pmsInfo.txt");
            BufferedWriter out = new BufferedWriter(fstream);
            out.write(pictureLocation + " 16 " + values + " " + filterValue);
            selectedValue = 16;
            //Close the output stream
            out.close();
        } catch (Exception e) {//Catch exception if any
            System.err.println("Error: " + e.getMessage());
        }

        //Close frame
        filterFrame.dispose();



    }//GEN-LAST:event_filterExitActionPerformed

    private void tintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tintActionPerformed

        JPanel temp = new JPanel();
        temp.setLayout(new BoxLayout(temp, BoxLayout.Y_AXIS));
        TintGroup.add(Green);
        TintGroup.add(Red);
        TintGroup.add(Blue);
        tintFrame.getContentPane().add(BorderLayout.CENTER, temp);
        tintFrame.setSize(350, 350);
        tintFrame.setVisible(true);


    }//GEN-LAST:event_tintActionPerformed

    private void tintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tintButtonActionPerformed

        try {
            // Create file 
            FileWriter fstream = new FileWriter("pmsInfo.txt");
            BufferedWriter out = new BufferedWriter(fstream);

            if (Red.isSelected()) {
                //                out.write(pictureLocation + " 9 nil");
                out.write(pictureLocation + " 9 "+getFilterSize());
                selectedValue = 9;
            }
            if (Green.isSelected()) {
                //                out.write(pictureLocation + " 8 nil");
                out.write(pictureLocation + " 8 "+getFilterSize());
                selectedValue = 8;
            }
            if (Blue.isSelected()) {
                //                out.write(pictureLocation + " 7 nil");
                out.write(pictureLocation + " 7 "+getFilterSize());
                selectedValue = 7;
            }
            //Close the output stream
            out.close();
        } catch (Exception e) {//Catch exception if any
            System.err.println("Error: " + e.getMessage());
        }


        tintFrame.dispose();
        submitActionPerformed(evt);

    }//GEN-LAST:event_tintButtonActionPerformed

    private void rotateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateActionPerformed

        JPanel temp = new JPanel();
        temp.setLayout(new BoxLayout(temp, BoxLayout.Y_AXIS));
        rotateFrame.getContentPane().add(BorderLayout.CENTER, temp);
        rotateFrame.setSize(350, 350);
        rotateFrame.setVisible(true);


    }//GEN-LAST:event_rotateActionPerformed

    private void rotateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotateButtonActionPerformed

        try {
            // Create file 
            FileWriter fstream = new FileWriter("pmsInfo.txt");
            BufferedWriter out = new BufferedWriter(fstream);
            if (degrees.getSelectedItem() == "90 Degrees to the Left") {
                out.write(pictureLocation + " 14 nil");
                selectedValue = 14;
            }
            if (degrees.getSelectedItem() == "90 Degrees to the Right") {
                out.write(pictureLocation + " 15 nil");
                selectedValue = 15;
            }
            if (degrees.getSelectedItem() == "180 Degrees") {
                out.write(pictureLocation + " 11 nil");
                selectedValue = 11;
            }

            //Close the output stream
            out.close();
        } catch (Exception e) {//Catch exception if any
            System.err.println("Error: " + e.getMessage());
        }

        rotateFrame.dispose();
    }//GEN-LAST:event_rotateButtonActionPerformed
    //Submit button calls sentinel executable 
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        //set .exe file path  
        //        EXEFILEPATH = ec.getExePath();
        //        EXEFILEPATH = new File("C:\\Users\\Michael\\School\\SoftwareEngineering2\\acl2-image-processor\\worker.exe");


        try {
            Runtime rt = Runtime.getRuntime();
            //run the int-sentinel executable
            Process p = rt.exec(EXEFILEPATH.toString());
            //wait for the executable to finish running
            p.waitFor();


        } catch (Exception e) {//Catch exception if any
            //            System.err.println("Error: " + e.getMessage());
            e.printStackTrace();
        }

        switch (selectedValue) {

            case 1:
                NEWPICNAME = "-bw.bmp";
                break;

            case 2:
                NEWPICNAME = "-blu-w.bmp";
                break;

            case 3:
                NEWPICNAME = "-grn-w.bmp";
                break;

            case 4:
                NEWPICNAME = "-red-w.bmp";
                break;

            case 5:
                NEWPICNAME = "-two-tone.bmp";
                break;

            case 6:
                NEWPICNAME = "-gray.bmp";
                break;

            case 7:
                NEWPICNAME = "-tint-blu.bmp";
                break;

            case 8:
                NEWPICNAME = "-tint-grn.bmp";
                break;

            case 9:
                NEWPICNAME = "-tint-red.bmp";
                break;

            case 10:
                NEWPICNAME = "-neg.bmp";
                break;

            case 11:
                NEWPICNAME = "-rot-180.bmp";
                break;

            case 12:
                NEWPICNAME = "-flipH.bmp";
                break;

            case 13:
                NEWPICNAME = "-flipV.bmp";
                break;

            case 14:
                NEWPICNAME = "-rot90-left.bmp";
                break;

            case 15:
                NEWPICNAME = "-rot90-right.bmp";
                break;

            case 16:
                NEWPICNAME = "-filter.bmp";
                break;

            case 17:
                NEWPICNAME = "-magnify.bmp";
                break;

            case 18:
                NEWPICNAME = "-16bit.bmp";
                break;

            case 19:
                NEWPICNAME = "-rle.bmp";
                break;

            case 20:
                NEWPICNAME = "-decomp.bmp";
                break;

            case 21:
                NEWPICNAME = "-crop.bmp";
                break;

            case 22:
                NEWPICNAME = "-magnifyHDR.bmp";
                break;

            case 23:
                NEWPICNAME = "-magnifyVert.bmp";
                break;

            case 24:
                NEWPICNAME = "-magnifyHrz.bmp";
                break;

            case 25:
                NEWPICNAME = "-sepia.bmp";
                break;

            case 26:
                NEWPICNAME = "-blur.bmp";
                break;

        }

        //set the new image location   
        createdFile = new File(NEWFILEPATH + NEWPICNAME);
        System.out.println((NEWFILEPATH + NEWPICNAME));

        chosenFile = createdFile;
        pictureLocation = chosenFile.getPath();
        int index = pictureLocation.indexOf(".");
        NEWFILEPATH = pictureLocation.substring(0, index);

        //display the new image
        setImage(createdFile);


    }//GEN-LAST:event_submitActionPerformed

    private void resizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resizeButtonActionPerformed

        JPanel temp = new JPanel();
        temp.setLayout(new BoxLayout(temp, BoxLayout.Y_AXIS));
        resizeFrame.getContentPane().add(BorderLayout.CENTER, temp);
        resizeFrame.setSize(350, 350);
        resizeFrame.setVisible(true);
        resizeGroup.add(doubleFileButton);
        resizeGroup.add(doubleViewButton);


    }//GEN-LAST:event_resizeButtonActionPerformed

    private void CompressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompressActionPerformed

        JPanel temp = new JPanel();
        temp.setLayout(new BoxLayout(temp, BoxLayout.Y_AXIS));
        compressFrame.getContentPane().add(BorderLayout.CENTER, temp);
        compressFrame.setSize(350, 350);
        compressFrame.setVisible(true);
        compressGroup.add(sixteenButton);
        compressGroup.add(rleComButton);
        compressGroup.add(rleDecomButton);

    }//GEN-LAST:event_CompressActionPerformed

    private void cropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cropActionPerformed

        try {
            // Create file 
            FileWriter fstream = new FileWriter("pmsInfo.txt");
            BufferedWriter out = new BufferedWriter(fstream);
            out.write(pictureLocation + " 21 120 120");
            selectedValue = 21;
            //Close the output stream
            out.close();
        } catch (Exception e) {//Catch exception if any
            System.err.println("Error: " + e.getMessage());
        }
    }//GEN-LAST:event_cropActionPerformed

    private void twoColorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoColorButtonActionPerformed

        ColorStringToNum cs = new ColorStringToNum();
        oneColor = twoColorChooser.getColor();
        String valueOne = cs.colorToNum(oneColor.toString(), 2);
        twoColor = oneColorChooser.getColor();
        String valueTwo = cs.colorToNum(twoColor.toString(), 2);

        try {
            // Create file 
            FileWriter fstream = new FileWriter("pmsInfo.txt");
            BufferedWriter out = new BufferedWriter(fstream);
            out.write(pictureLocation + " 5 " + valueOne + " " + valueTwo);
            selectedValue = 5;
            //Close the output stream
            out.close();
        } catch (Exception e) {//Catch exception if any
            System.err.println("Error: " + e.getMessage());
        }

        twoToneFrame.dispose();
    }//GEN-LAST:event_twoColorButtonActionPerformed

    private void originalPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_originalPictureActionPerformed

        setImage(originalFile);

    }//GEN-LAST:event_originalPictureActionPerformed

    private void submitStretchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitStretchActionPerformed


        try {
            // Create file 
            FileWriter fstream = new FileWriter("pmsInfo.txt");
            BufferedWriter out = new BufferedWriter(fstream);
            if (Vertical.isSelected()) {
                out.write(pictureLocation + " 23 nil");
                selectedValue = 23;
            }
            if (Horizontal.isSelected()) {
                out.write(pictureLocation + " 24 nil");
                selectedValue = 24;
            }
            //Close the output stream
            out.close();
        } catch (Exception e) {//Catch exception if any
            System.err.println("Error: " + e.getMessage());
        }

        stretchFrame.dispose();
    }//GEN-LAST:event_submitStretchActionPerformed

    private void submitResizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitResizeActionPerformed

        try {
            // Create file 
            FileWriter fstream = new FileWriter("pmsInfo.txt");
            BufferedWriter out = new BufferedWriter(fstream);
            if (doubleViewButton.isSelected()) {
                out.write(pictureLocation + " 22 nil");
                selectedValue = 22;
            }
            if (doubleFileButton.isSelected()) {
                out.write(pictureLocation + " 17 nil");
                selectedValue = 17;
            }
            //Close the output stream
            out.close();
        } catch (Exception e) {//Catch exception if any
            System.err.println("Error: " + e.getMessage());
        }

        resizeFrame.dispose();
    }//GEN-LAST:event_submitResizeActionPerformed

    private void cwSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cwSubmitActionPerformed
        try {
            //Create file to be read by sentinel
            FileWriter fstream = new FileWriter("pmsInfo.txt");
            BufferedWriter out = new BufferedWriter(fstream);
            if (blackWhiteButton.isSelected()) {
                //                out.write(pictureLocation + " 1 " + cwSlider.getValue());
                out.write(pictureLocation + " 1 "+getFilterSize());
                selectedValue = 1;
            }
            if (blueWhiteButton.isSelected()) {
                out.write(pictureLocation + " 2 " + cwSlider.getValue());
                selectedValue = 2;
            }
            if (greenWhiteButton.isSelected()) {
                out.write(pictureLocation + " 3 " + cwSlider.getValue());
                selectedValue = 3;
            }
            if (redWhiteButton.isSelected()) {
                out.write(pictureLocation + " 4 " + cwSlider.getValue());
                selectedValue = 4;
            }
            //Close the output stream
            out.close();

        } catch (Exception e) {//Catch exception if any
            //            System.err.println("Error: " + e.getMessage());
            e.printStackTrace();
        }

        cwFrame.dispose();
        submitActionPerformed(evt);
    }//GEN-LAST:event_cwSubmitActionPerformed

    private void flipSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flipSubmitActionPerformed

        try {
            //Create file to be read by sentinel
            FileWriter fstream = new FileWriter("pmsInfo.txt");
            BufferedWriter out = new BufferedWriter(fstream);
            if (verticalButton.isSelected()) {
                out.write(pictureLocation + " 13 nil");
                selectedValue = 13;
            }
            if (horizontalButton.isSelected()) {
                out.write(pictureLocation + " 12 nil");
                selectedValue = 12;
            }
            //Close the output stream
            out.close();

        } catch (Exception e) {//Catch exception if any
            System.err.println("Error: " + e.getMessage());
        }

        flipFrame.dispose();

    }//GEN-LAST:event_flipSubmitActionPerformed

    private void flipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flipActionPerformed

        JPanel temp = new JPanel();
        temp.setLayout(new BoxLayout(temp, BoxLayout.Y_AXIS));
        flipFrame.getContentPane().add(BorderLayout.CENTER, temp);
        flipFrame.setSize(350, 350);
        flipFrame.setVisible(true);
        flipGroup.add(verticalButton);
        flipGroup.add(horizontalButton);


    }//GEN-LAST:event_flipActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            // Create file 
            FileWriter fstream = new FileWriter("pmsInfo.txt");
            BufferedWriter out = new BufferedWriter(fstream);
            if (sixteenButton.isSelected()) {
                out.write(pictureLocation + " 18 nil");
                selectedValue = 18;
            }
            if (rleComButton.isSelected()) {
                out.write(pictureLocation + " 19 nil");
                selectedValue = 19;
            }
            if (rleDecomButton.isSelected()) {
                out.write(pictureLocation + " 20 nil");
                selectedValue = 20;
            }
            //Close the output stream
            out.close();
        } catch (Exception e) {//Catch exception if any
            System.err.println("Error: " + e.getMessage());
        }

        compressFrame.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    //formats the image to be displayed in 
    //the main frame of the GUI in a jLabel 
    public void setImage(File selectedFile) 
    {
        try 
        {
            image = ImageIO.read(selectedFile);
            repaint();
        } 
        catch (IOException ex) 
        {
            //            System.err.println("Error: " + ex.getMessage());
            ex.printStackTrace();
        }

        //picLabel.setIcon(new ImageIcon(image));
        //setVisible(true);
    }


    @SuppressWarnings("serial")
    class ImagePanel extends JPanel
    {
        public ImagePanel ()
        {
            setSize(400,400);
            setVisible(true);

            addMouseListener(new MouseListener()
            {
                @Override
                public void mouseClicked(MouseEvent e){}

                @Override
                public void mousePressed(MouseEvent e)
                {
                    selectAll.setSelected(false);
                    startPos = new Point(e.getX(),e.getY());
                    endPos = new Point(e.getX(),e.getY());
                }

                @Override
                public void mouseReleased(MouseEvent e)
                {
                    selectAll.setSelected(false);
                    endPos = new Point(e.getX(),e.getY());
                    if (endPos.x < startPos.x)
                    {
                        int temp = endPos.x;
                        endPos.x = startPos.x;
                        startPos.x = temp;
                    }
                    if (endPos.y < startPos.y)
                    {
                        int temp = endPos.y;
                        endPos.y = startPos.y;
                        startPos.y = temp;
                    }
                }

                @Override
                public void mouseEntered(MouseEvent e){}

                @Override
                public void mouseExited(MouseEvent e){}
            });
            
            addMouseMotionListener(new MouseMotionListener()
            {

                @Override
                public void mouseDragged(MouseEvent e)
                {
                    selectAll.setSelected(false);
                    endPos = new Point(e.getX(),e.getY());
                }

                @Override
                public void mouseMoved(MouseEvent e) {}
                
            });

            addMouseMotionListener(new MouseMotionListener()
            {
                @Override
                public void mouseDragged(MouseEvent e){}

                @Override
                public void mouseMoved(MouseEvent e){}                
            });


            Timer repaint = new Timer(50, new PaintTimer());
            repaint.start();
        }


        class PaintTimer implements ActionListener
        {
            @Override
            public void actionPerformed(ActionEvent e)
            {
                repaint();
            }
        }



        protected void paintComponent (Graphics g)
        {
            super.paintComponent(g);

            setBackground(Color.black);

            if (image != null)
            {
                this.setSize(image.getWidth(),image.getHeight());
                g.drawImage(image,0,0,null);
            }

            g.setColor(Color.red);
            if (endPos.x < startPos.x)
            {
                if (endPos.y < startPos.y)
                    g.drawRect(endPos.x, endPos.y, Math.abs(endPos.x-startPos.x), Math.abs(endPos.y-startPos.y));
                else
                    g.drawRect(endPos.x, startPos.y, Math.abs(endPos.x-startPos.x), Math.abs(endPos.y-startPos.y));
            }
            else if (endPos.y < startPos.y)
                g.drawRect(startPos.x, endPos.y, Math.abs(endPos.x-startPos.x), Math.abs(endPos.y-startPos.y));
            else
                g.drawRect(startPos.x, startPos.y, Math.abs(endPos.x-startPos.x), Math.abs(endPos.y-startPos.y));
        }

    }



    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Blue;
    private javax.swing.JButton CW;
    private javax.swing.JButton Compress;
    private javax.swing.JRadioButton Green;
    private javax.swing.JRadioButton Horizontal;
    private javax.swing.JRadioButton Red;
    private javax.swing.ButtonGroup StretchGroup;
    private javax.swing.ButtonGroup TintGroup;
    private javax.swing.JRadioButton Vertical;
    private javax.swing.JRadioButton blackWhiteButton;
    private javax.swing.JRadioButton blueWhiteButton;
    private javax.swing.JButton choosePicture;
    private javax.swing.JFrame compressFrame;
    private javax.swing.ButtonGroup compressGroup;
    private javax.swing.JLabel compressoinLabel;
    private javax.swing.JButton crop;
    private javax.swing.JFrame cwFrame;
    private javax.swing.ButtonGroup cwGroup;
    private javax.swing.JLabel cwLabel;
    private javax.swing.JSlider cwSlider;
    private javax.swing.JButton cwSubmit;
    private javax.swing.JComboBox<String> degrees;
    private javax.swing.JRadioButton doubleFileButton;
    private javax.swing.JRadioButton doubleViewButton;
    private javax.swing.JButton exit;
    private javax.swing.JButton filterButton;
    private javax.swing.JColorChooser filterColorChooser;
    public javax.swing.JButton filterExit;
    private javax.swing.JFrame filterFrame;
    private javax.swing.JLabel filterLabel;
    private javax.swing.JLabel filterLabel1;
    private javax.swing.JSlider filterScale;
    private javax.swing.JButton flip;
    private javax.swing.JFrame flipFrame;
    private javax.swing.ButtonGroup flipGroup;
    private javax.swing.JLabel flipLabel;
    private javax.swing.JButton flipSubmit;
    private javax.swing.JButton grayScale;
    private javax.swing.JRadioButton greenWhiteButton;
    private javax.swing.JRadioButton horizontalButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mainTitle;
    private javax.swing.JButton negatize;
    private javax.swing.JColorChooser oneColorChooser;
    private javax.swing.JButton originalPicture;
    private javax.swing.JLabel picLabel;
    private javax.swing.JRadioButton redWhiteButton;
    private javax.swing.JButton resizeButton;
    private javax.swing.JFrame resizeFrame;
    private javax.swing.ButtonGroup resizeGroup;
    private javax.swing.JLabel resizeLabel;
    private javax.swing.JRadioButton rleComButton;
    private javax.swing.JRadioButton rleDecomButton;
    private javax.swing.JButton rotate;
    private javax.swing.JButton rotateButton;
    private javax.swing.JFrame rotateFrame;
    private javax.swing.JRadioButton sixteenButton;
    private javax.swing.JButton stretch;
    private javax.swing.JFrame stretchFrame;
    private javax.swing.JLabel stretchLabel;
    private javax.swing.JButton submit;
    private javax.swing.JToggleButton submitResize;
    private javax.swing.JToggleButton submitStretch;
    private javax.swing.JButton tint;
    private javax.swing.JButton tintButton;
    private javax.swing.JFrame tintFrame;
    private javax.swing.JLabel tintLabel;
    private javax.swing.JToggleButton twoColorButton;
    private javax.swing.JColorChooser twoColorChooser;
    private javax.swing.JButton twoTone;
    private javax.swing.JFrame twoToneFrame;
    private javax.swing.JRadioButton verticalButton;
    private javax.swing.JButton sepia;
    private javax.swing.JButton upload;
    private javax.swing.JButton blur;
    private javax.swing.JCheckBox selectAll;
    // End of variables declaration//GEN-END:variables


    private String getFilterSize ()
    {
        return (startPos.x+" "+(image.getHeight()-startPos.y-Math.abs(endPos.y-startPos.y))+" "+
                (Math.abs(endPos.x-startPos.x))+" "+(Math.abs(endPos.y-startPos.y)) +" "+image.getWidth()+" "+image.getHeight());
    }
}
